// Question bank. Each item: id, q (stem), optional code/sub, o (4 options), a (answer letter), s (solution lines)

const secA = [
  { id: 'A1', q: 'What is printed?', code: [
    't = ([1], [2])', 'try:', '    t[0] += [3]', 'except TypeError:', '    t[1].append(len(t[0]))', 'print(t)'],
    o: ['([1], [2, 1])', '([1, 3], [2, 2])', '([1, 3], [2])', 'An uncaught TypeError'], a: 'b',
    s: ['t[0] += [3] runs as t[0] = t[0].__iadd__([3]). The list is extended in place to [1, 3] first, and only then does the assignment into the tuple raise TypeError.',
        'The handler appends len(t[0]) = 2 to t[1], so the output is ([1, 3], [2, 2]).'] },
  { id: 'A2', q: 'What is printed?', code: [
    "d = {1: 'a', True: 'b', 1.0: 'c', 0: 'd', False: 'e', 0.0+0j: 'f'}", 'print(len(d), d[1], list(d.keys()))'],
    o: ['6 a [1, True, 1.0, 0, False, 0j]', '2 c [1.0, 0j]', '2 a [1, 0]', '2 c [1, 0]'], a: 'd',
    s: ['1, True and 1.0 are equal and hash the same, so they are one key. A dict keeps the first key object (1) but overwrites the value, ending with \'c\'.',
        'In the same way, 0, False and 0j collapse into the key 0 with value \'f\'. The output is 2 c [1, 0].'] },
  { id: 'A3', q: 'What is printed?', code: [
    'class A:', "    def f(self): return 'A'", 'class B(A):', "    def f(self): return 'B' + super().f()",
    'class C(A):', "    def f(self): return 'C' + super().f()", 'class D(B, C):',
    "    def f(self): return 'D' + super(B, self).f()", 'print(D().f())'],
    o: ['DBCA', 'DCA', 'DA', 'DBA'], a: 'b',
    s: ['The MRO of D is D → B → C → A. super(B, self) starts the search after B, so it calls C.f and skips B entirely.',
        'Inside C.f, super() (self is still a D) continues after C, which is A. The result is "D" + "C" + "A" = DCA.'] },
  { id: 'A4', q: 'What is printed?', code: [
    'def gen():', '    total = 0', '    while True:', '        try:', '            x = yield total',
    '        except ValueError:', '            total = -total', '            continue',
    '        if x is None:', '            return total', '        total += x', '',
    'g = gen(); out = [next(g)]', 'out.append(g.send(4))', 'out.append(g.throw(ValueError))',
    'out.append(g.send(10))', 'try:', '    next(g)', 'except StopIteration as e:', '    out.append(e.value)', 'print(out)'],
    o: ['[0, 4, -4, 6, 6]', '[0, 4, 4, 14, 14]', '[0, 4, -4, 6, None]', '[0, 4, 0, 10, 10]'], a: 'a',
    s: ['next(g) yields 0. send(4) makes total 4, and the loop yields 4.',
        'throw(ValueError) raises the exception at the paused yield. It is caught, total becomes −4, and continue yields −4.',
        'send(10) makes total 6 and yields 6. next(g) sends None, so the generator returns 6, which arrives as StopIteration.value. The list is [0, 4, −4, 6, 6].'] },
  { id: 'A5', q: 'What is printed?', code: [
    'x = 1', 'class K:', '    x = 2', '    y = [x for _ in range(2)]', '    z = (lambda: x)()', 'print(K.y, K.z)'],
    o: ['[2, 2] 2', '[1, 1] 1', '[2, 2] 1', '[1, 1] 2'], a: 'b',
    s: ['Names bound in a class body are not visible to nested scopes. The comprehension and the lambda are both nested scopes, so they skip the class-level x = 2 and find the global x = 1.',
        'Python 3.12 inlines comprehensions (PEP 709) but keeps this rule for class bodies. The output is [1, 1] 1.'] },
  { id: 'A6', q: 'What is printed?', code: [
    'class P:', '    def __init__(s, v): s.v = v', '    def __eq__(s, o): return s.v % 3 == o.v % 3',
    '    def __hash__(s): return s.v % 2', 'S = {P(i) for i in range(10)}', 'print(len(S))'],
    o: ['2', '3', '6', '10'], a: 'c',
    s: ['A set treats two objects as duplicates only when their hashes are equal and __eq__ is true, that is when v % 2 and v % 3 both match, which means v % 6 matches.',
        'The values 0 to 9 cover all 6 residues mod 6, so the set has 6 elements.'] },
  { id: 'A7', q: 'What is printed?', code: [
    'class Counter:', '    count = 0', '    def __init__(self):', '        self.count += 1',
    '        type(self).count += 2', 'a = Counter(); b = Counter()', 'print(a.count, b.count, Counter.count)'],
    o: ['1 3 4', '1 1 4', '3 3 4', '1 3 2'], a: 'a',
    s: ['self.count += 1 reads the class attribute and then creates an instance attribute.',
        'For a: the instance gets 0 + 1 = 1, and the class goes from 0 to 2. For b: it reads the class value 2, so the instance gets 3, and the class goes to 4. The output is 1 3 4.'] },
  { id: 'A8', q: 'What is printed in total?', code: [
    'def deco(tag):', "    print(tag, end='')", '    def wrap(fn):', "        print(tag.lower(), end='')",
    '        def inner(*a):', "            print(tag, end='')", '            return fn(*a)', '        return inner',
    '    return wrap', '', "@deco('A')", "@deco('B')", "def h(): print('h', end='')", 'h()'],
    o: ['ABabABh', 'ABbaBAh', 'BAbaBAh', 'ABbaABh'], a: 'd',
    s: ['The decorator expressions are evaluated top to bottom first, printing A and then B.',
        'The decorators are then applied bottom-up: B\'s wrap prints b, then A\'s wrap prints a.',
        'Calling h runs the outermost wrapper first, printing A, then B, then h. The full output is ABbaABh.'] },
  { id: 'A9', q: 'What is printed?', code: [
    "data = ['bb', 'a', 'ccc', 'ab', 'b', 'ba']", 'data.sort(key=len)',
    'data.sort(key=lambda s: s[-1], reverse=True)', 'print(data)'],
    o: ["['ccc', 'bb', 'ab', 'b', 'ba', 'a']", "['ccc', 'ab', 'bb', 'b', 'ba', 'a']",
        "['ccc', 'b', 'bb', 'ab', 'a', 'ba']", "['ccc', 'b', 'ab', 'bb', 'a', 'ba']"], a: 'c',
    s: ['The stable sort by length gives a, b, bb, ab, ba, ccc.',
        'reverse=True still keeps the sort stable: items with equal keys stay in their existing order. Grouping by last character from c down to a gives ccc | b, bb, ab | a, ba.'] },
  { id: 'A10', q: 'What is printed?', code: [
    'it = iter(range(10))', 'pairs = list(zip(it, it))', 'it2 = iter(range(10))',
    'res = [x for x in it2 if x + 2 in it2]', 'print(len(pairs), res)'],
    o: ['10 [0, 3, 6]', '5 [0, 3, 6]', '5 [0, 3, 6, 9]', '5 []'], a: 'b',
    s: ['zip(it, it) takes two items from the same iterator for each tuple, so there are 5 pairs.',
        'x + 2 in it2 consumes it2 until it finds x + 2. For x = 0 it consumes 1 and 2 (True), the loop continues with x = 3, which consumes 4 and 5, and x = 6 consumes 7 and 8. For x = 9 it exhausts the iterator (False). res = [0, 3, 6].'] },
];

const secML = [
  { id: 'ML1', q: 'A bank\'s fraud model scores 100,000 transactions, of which 0.5% are fraudulent. A missed fraud costs ₹10,000 and every flagged transaction that turns out to be genuine costs ₹200 in manual review. Threshold T1 gives recall 80% and precision 20%. Threshold T2 gives recall 60% and precision 50%. Which threshold should the bank choose, and how much does it save compared with the other?',
    o: ['T2, saving ₹7.4 lakh', 'T1, saving ₹7.4 lakh', 'T1, saving ₹2.6 lakh', 'T2, saving ₹2.6 lakh'], a: 'b',
    s: ['There are 500 frauds.',
        'T1: TP = 400, FN = 100, FP = 400/0.20 − 400 = 1,600. Cost = 100 × 10,000 + 1,600 × 200 = ₹13.2 lakh.',
        'T2: TP = 300, FN = 200, FP = 300/0.50 − 300 = 300. Cost = 200 × 10,000 + 300 × 200 = ₹20.6 lakh.',
        'T1 is cheaper by ₹7.4 lakh even though its precision is much worse, because missed frauds dominate the cost.'] },
  { id: 'ML2', q: 'A team working on an imbalanced medical dataset first applies StandardScaler and then SMOTE oversampling to the full dataset. After that they run 5-fold cross-validation and get ROC-AUC 0.97. On new hospital data the model scores 0.71. What is the most likely main cause of the gap?',
    o: ['StandardScaler was fitted on the full data, leaking the mean and variance of the validation folds',
        'Five folds are too few for a reliable estimate',
        'SMOTE ran before splitting, so synthetic training points were interpolated from validation-fold patients',
        'ROC-AUC is unreliable on imbalanced data'], a: 'c',
    s: ['SMOTE creates each synthetic minority sample by interpolating between a real sample and its neighbours. Running it before the split puts near-copies of validation patients into the training folds, so CV rewards memorisation and the score is heavily inflated.',
        'Scaler leakage only shifts means and variances slightly and cannot explain a 0.26 drop in AUC. Five folds are standard. ROC-AUC is insensitive to class imbalance.',
        'The fix is to put the scaler and SMOTE inside the CV pipeline, for example with imblearn.Pipeline.'] },
  { id: 'ML3', q: 'A speech model is trained on clean studio recordings and deployed on noisy phone calls. Human-level error is 1%. The team measures training error 3%, training-dev error (unseen studio data) 4% and dev error (phone calls) 14%. What should they fix first?',
    o: ['Avoidable bias: use a bigger model',
        'Variance: add regularisation or more studio data',
        'Overfitting to the dev set: get a fresh dev set',
        'Data mismatch: get or synthesise training data that resembles noisy phone audio'], a: 'd',
    s: ['Avoidable bias = 3 − 1 = 2%. Variance = 4 − 3 = 1%. Data mismatch = 14 − 4 = 10%.',
        'The largest gap is between training-dev and dev, which differ only in distribution. The team should fix the mismatch first, for example by adding noise augmentation or collecting phone-call data (Ng, "Machine Learning Yearning").'] },
  { id: 'ML4', q: 'The network is ŷ = σ(w₂ · ReLU(w₁x + b₁)) with binary cross-entropy loss. The values are x = 2, w₁ = 0.5, b₁ = −0.5, w₂ = 2 and label y = 1. What is ∂L/∂w₁? (σ(1) ≈ 0.731)',
    o: ['−1.08', '−0.54', '−0.13', '−2.15'], a: 'a',
    s: ['Forward pass: h = ReLU(0.5 × 2 − 0.5) = 0.5, z = 2 × 0.5 = 1, ŷ = σ(1) = 0.731.',
        'For sigmoid with BCE, ∂L/∂z = ŷ − y = −0.269. Then ∂L/∂h = −0.269 × w₂ = −0.538.',
        'The ReLU is active, so ∂h/∂w₁ = x = 2. ∂L/∂w₁ = −0.538 × 2 = −1.076 ≈ −1.08.'] },
  { id: 'ML5', q: 'In a churn model, a random forest\'s built-in impurity-based feature importance ranks customer_id at the top. customer_id is a random integer that is unique per customer. Dropping the column does not change test accuracy at all. What explains this, and how should importance be measured instead?',
    o: ['customer_id truly carries signal, so keep it and report it',
        'Impurity importance (MDI) is computed on training data and favours high-cardinality features that allow many splits. Use permutation importance on held-out data instead.',
        'Random forests cannot handle integer IDs, so one-hot encode the column',
        'The trees are too shallow. Increase max_depth.'], a: 'b',
    s: ['Mean decrease in impurity is measured on the training set. A unique-valued feature offers many split points and can lower impurity by memorising individual rows, so it looks important without generalising.',
        'Permutation importance (or drop-column importance) on held-out data measures the real effect on predictions, which here is about zero, matching the unchanged test accuracy.'] },
  { id: 'ML6', q: 'What is the VC dimension of the hypothesis class "union of two intervals" on the real line?',
    o: ['2', '3', '4', '5'], a: 'c',
    s: ['On 4 points, any labelling has at most two separate blocks of positives, and two intervals can cover them, so 4 points are shattered.',
        'On 5 points, the labelling + − + − + needs three intervals, so no set of 5 points can be shattered. VC dimension = 4.'] },
  { id: 'ML7', q: 'A Naive Bayes spam filter sees 20% spam. The word "free" appears in 30% of spam and 2% of ham. The word "winner" appears in 20% of spam and 1% of ham. An email contains both words. What is the posterior probability that it is spam?',
    o: ['0.600', '0.940', '0.999', '0.987'], a: 'd',
    s: ['Spam: 0.2 × 0.3 × 0.2 = 0.012. Ham: 0.8 × 0.02 × 0.01 = 0.00016.',
        'P(spam | words) = 0.012 / (0.012 + 0.00016) = 0.987.'] },
  { id: 'ML8', q: 'An engineer trains with Adam (β₁ = 0.9, β₂ = 0.999, η = 0.001, ε ≈ 0). On the very first step, parameter P gets gradient 0.004 and parameter Q gets gradient 40. What are the magnitudes of their first updates?',
    o: ['0.000004 and 0.04', '0.001 and 0.001', '0.00316 and 0.00316', '0.001 and 0.04'], a: 'b',
    s: ['At step 1, m₁ = 0.1g and v₁ = 0.001g². Bias correction gives m̂ = m₁/(1 − 0.9) = g and v̂ = v₁/(1 − 0.999) = g².',
        'The update is η · g / √(g²) = η · sign(g), so both magnitudes are 0.001 whatever the gradient scale. Without bias correction the answer would be 0.00316, which is a trap option.'] },
];

const secGA = [
  { id: 'GA1', q: 'A RAG chatbot over company policies has retrieval recall@5 = 70% and recall@20 = 95%. End-to-end answer accuracy is 68% with the top 5 chunks and 62% with the top 20 chunks. Context length is not a constraint. Which single change is most likely to raise accuracy?',
    o: ['Pass the top 50 chunks so the answer is almost always present',
        'Retrieve 20 chunks, rerank them with a cross-encoder, and pass the best 5 to the LLM',
        'Increase the chunk size from 512 to 2,048 tokens',
        'Switch to an embedding model with a higher dimension'], a: 'b',
    s: ['recall@20 = 95% shows that the evidence is usually retrieved. Accuracy falls when more chunks are passed, which shows the generator is distracted by irrelevant context ("Lost in the Middle", Liu et al., 2023).',
        'Reranking 20 candidates down to the best 5 keeps close to 95% recall while giving the model a short, focused context.',
        'Passing more chunks makes the distraction worse. Larger chunks and bigger embeddings don\'t fix the ranking problem.'] },
  { id: 'GA2', q: 'You serve a 70B model on one 80 GB GPU. After loading int8 weights and reserving activation memory, exactly 10 GiB remain for the KV cache, which is stored in fp16. The model has 80 layers, 64 query heads, 8 KV heads (GQA) and head dimension 128. Every request uses a 4,096-token context. How many requests can run concurrently?',
    o: ['64', '16', '8', '1'], a: 'c',
    s: ['KV per token = 2 (K and V) × 80 layers × 8 KV heads × 128 × 2 bytes = 327,680 bytes = 320 KiB.',
        '10 GiB / 320 KiB = 32,768 tokens, and 32,768 / 4,096 = 8 requests.',
        'With full multi-head attention (64 KV heads) the cache would be 8 times larger, leaving room for only 1 request. This is why GQA matters for serving.'] },
  { id: 'GA3', q: 'A startup says: "Our MoE model has 8 experts per layer with top-2 routing and only 12.8B active parameters, so it needs the same GPU memory as a 13B dense model." Shared (non-expert) parameters total 1.6B, and each expert has 5.6B parameters summed across all layers. What are the bf16 weight memory and the approximate forward FLOPs per token?',
    o: ['92.8 GB and 25.6 GFLOPs', '25.6 GB and 25.6 GFLOPs', '92.8 GB and 92.8 GFLOPs', '112 GB and 28 GFLOPs'], a: 'a',
    s: ['Any token can be routed to any expert, so every expert must be in memory: 1.6 + 8 × 5.6 = 46.4B parameters × 2 bytes = 92.8 GB.',
        'Each token only runs the shared weights plus 2 experts: 1.6 + 2 × 5.6 = 12.8B parameters. At about 2 FLOPs per parameter that is 25.6 GFLOPs.',
        'The claim confuses compute per token with memory.'] },
  { id: 'GA4', q: 'You fine-tune a 32-layer model (d_model = 4096) with LoRA of rank 16 on W_q and W_v, which are each 4096 × 4096. After training you merge the adapters into the base weights. How many parameters were trainable, and how much extra latency does the merged model have at inference?',
    o: ['4.19 M, none', '8.39 M, about 0.4%', '16.8 M, none', '8.39 M, none'], a: 'd',
    s: ['Each adapted matrix adds A (16 × 4096) and B (4096 × 16), which is 16 × 8,192 = 131,072 parameters. × 2 matrices × 32 layers = 8,388,608 ≈ 8.39 M.',
        'Merging computes W′ = W + BA, which has the same shape as W. There are no extra matrix multiplications, so there is no added latency (Hu et al., 2021).'] },
  { id: 'GA5', q: 'A 2-D RoPE rotates each vector by θ = π/4 per position. The query q = (1, 0) sits at position 7 and the key k = (1, 0) sits at position 3. What is the attention score q·k after rotation?',
    o: ['0', '−1', '1', '√2 / 2'], a: 'b',
    s: ['RoPE rotates q by 7θ and k by 3θ. The dot product of two rotated vectors depends only on the angle between them: cos((7 − 3)θ) = cos(π) = −1.',
        'This is the relative-position property of RoPE (Su et al., 2021).'] },
  { id: 'GA6', q: 'A team sets temperature 0.5 and nucleus sampling with top-p = 0.8 to make responses "more focused". At one step the logits for three candidate tokens are [2, 1, 0]. What is the probability of sampling the second token?',
    o: ['0.117', '0.269', '0', '0.119'], a: 'c',
    s: ['Temperature 0.5 turns the logits into [4, 2, 0]. The softmax gives 0.867, 0.117 and 0.016.',
        'Nucleus sampling keeps the smallest set whose cumulative probability is at least 0.8. The top token alone (0.867) already passes that, so only it survives, and the second token has probability 0.',
        '0.269 is the answer at temperature 1, which is a trap option.'] },
  { id: 'GA7', q: 'A lab has about 6 × 10²³ FLOPs of training compute. Plan A trains a 175B-parameter model on 570B tokens. Plan B trains a 70B-parameter model on 1.4T tokens. Which plan should reach the lower loss, and which is cheaper to serve?',
    o: ['A for lower loss, B for cheaper serving', 'A on both', 'B on both', 'Equal loss, B cheaper to serve'], a: 'c',
    s: ['Both plans cost about the same: 6ND = 6 × 175e9 × 570e9 ≈ 5.99e23 and 6 × 70e9 × 1.4e12 ≈ 5.88e23.',
        'Chinchilla (Hoffmann et al., 2022) found the compute-optimal ratio is about 20 tokens per parameter. Plan A has about 3.3 tokens per parameter and is under-trained, while Plan B has 20. Chinchilla itself (70B on 1.4T tokens) beat the 280B Gopher on the same compute.',
        'Plan B also has 2.5× fewer parameters, so it is cheaper to serve.'] },
  { id: 'GA8', q: 'Which of these is permutation-equivariant with respect to input token order?',
    sub: ['(i) Encoder self-attention with no positional encoding',
          '(ii) Causal (decoder) self-attention with no positional encoding',
          '(iii) Encoder self-attention with sinusoidal positional encoding'],
    o: ['Only (i)', '(i) and (ii)', '(i) and (iii)', 'None'], a: 'a',
    s: ['Without positional information, self-attention is a symmetric function of the set of tokens, so permuting the input permutes the output the same way.',
        'A causal mask depends on token index, which breaks equivariance for (ii). Positional encodings break it for (iii). Only (i) is permutation-equivariant.'] },
];

const secAG = [
  { id: 'AG1', q: 'Your team automates a 10-step invoice-processing workflow with an LLM agent. Each step succeeds independently with probability 0.95. You add a verifier after every step that catches 80% of failed steps and never flags a correct one. When it catches a failure, the agent retries that step once, and the retry also succeeds with probability 0.95. What is the end-to-end success rate?',
    o: ['0.817', '0.951', '0.599', '0.886'], a: 'd',
    s: ['Each step now succeeds with probability 0.95 + (0.05 × 0.80 × 0.95) = 0.988.',
        'Over 10 steps: 0.988¹⁰ ≈ 0.886. Without the verifier it would be 0.95¹⁰ ≈ 0.599. Small per-step gains compound a lot.'] },
  { id: 'AG2', q: 'A ReAct research agent runs on an API priced at $3 per million input tokens, and cached prefix reads cost 10% of that. Ignore output tokens and any cache-write premium. The system prompt plus task is 2,000 tokens. Each step appends 1,000 tokens, and every call re-sends the whole conversation. The agent makes 10 calls, and everything sent in an earlier call is a cache hit. What is the total input cost with caching?',
    o: ['$0.195', '$0.049', '$0.033', '$0.020'], a: 'b',
    s: ['Call k sends 2,000 + 1,000(k − 1) tokens, so the total is 20,000 + 45,000 = 65,000 tokens ($0.195 without caching).',
        'With caching, only new tokens are full price: 2,000 on call 1 and 1,000 on each of calls 2–10, which is 11,000 tokens. The other 54,000 tokens are cache reads.',
        'Cost = 11,000 × $3/M + 54,000 × $0.30/M = $0.033 + $0.0162 ≈ $0.049.'] },
  { id: 'AG3', q: 'A travel-planning agent calls four tools. Flights (A) takes 2 s, Hotels (B) takes 3 s and Weather (D) takes 4 s, and these are independent. Pricing (C) takes 1 s and needs the outputs of A and B. Each LLM turn takes 1 s. The model can issue several tool calls in one turn, and all results of a batch come back together before its next turn. After all tools finish, one final LLM turn writes the answer. What is the minimum end-to-end latency?',
    o: ['7 s', '10 s', '8 s', '15 s'], a: 'c',
    s: ['Turn 1 (1 s) issues A, B and D together, and the batch returns after max(2, 3, 4) = 4 s. Turn 2 (1 s) issues C (1 s). Turn 3 (1 s) writes the answer.',
        'Total: 1 + 4 + 1 + 1 + 1 = 8 s.',
        'Delaying D so it runs with C gives 1 + 3 + 1 + 4 + 1 = 10 s. Running everything sequentially gives 5 turns + 10 s of tools = 15 s.'] },
  { id: 'AG4', q: 'A math-tutor agent uses self-consistency. It draws 5 independent reasoning paths, and each reaches the correct answer with probability 0.6. Wrong paths never agree with each other. The agent returns the plurality answer, and a tie counts as a failure. What is the probability that it returns the correct answer?',
    o: ['0.913', '0.600', '0.683', '0.990'], a: 'a',
    s: ['Every wrong answer gets exactly one vote. The correct answer wins as soon as at least 2 paths agree on it. With exactly 1 correct path, all five answers tie at one vote each, which counts as a failure.',
        'P(at least 2 correct) = 1 − 0.4⁵ − 5(0.6)(0.4⁴) = 1 − 0.01024 − 0.0768 = 0.913.',
        '0.683 is P(at least 3 correct), which would be the answer only if a strict majority were required. It is a trap option.'] },
  { id: 'AG5', q: 'A vendor ran its customer-support agent 10 times on the same task and it succeeded 6 times. The vendor advertises "pass@3 = 96.7%". Using the unbiased estimators from n = 10 and c = 6, what are pass@3 (Chen et al., 2021) and pass^3 (τ-bench, Yao et al., 2024)?',
    o: ['0.936 and 0.216', '0.967 and 0.167', '0.784 and 0.216', '0.600 and 0.600'], a: 'b',
    s: ['pass@3 is the chance that at least one of 3 attempts succeeds: 1 − C(4, 3)/C(10, 3) = 1 − 4/120 = 0.967.',
        'pass^3 is the chance that all 3 attempts succeed: C(6, 3)/C(10, 3) = 20/120 = 0.167.',
        'A support bot has to work for every customer, so pass^k is the relevant reliability metric and the advertised 96.7% is misleading. 0.936 and 0.216 come from treating the samples as drawn with replacement, which is a trap option.'] },
  { id: 'AG6', q: 'A Tree-of-Thoughts agent solves a puzzle with breadth-first search. Each state proposes 3 candidate thoughts, the search depth is 3, and after scoring only the best 2 states are kept at each level. How many thought states are generated in total?',
    o: ['39', '12', '18', '15'], a: 'd',
    s: ['Level 1: the root proposes 3 thoughts, and 2 are kept. Level 2: 2 × 3 = 6 thoughts, and 2 are kept. Level 3: 2 × 3 = 6 thoughts.',
        'Total = 3 + 6 + 6 = 15. The full tree would have 3 + 9 + 27 = 39.'] },
  { id: 'AG7', q: 'In the Model Context Protocol (MCP), the server primitives Tools, Resources and Prompts are designed to be controlled by whom, respectively?',
    o: ['User, model, application', 'Application, model, user', 'Model, application, user', 'Model, user, application'], a: 'c',
    s: ['In the MCP specification, tools are model-controlled (the LLM decides when to call them), resources are application-controlled (the host decides what context to attach), and prompts are user-controlled (the user picks templates, for example slash commands).'] },
  { id: 'AG8', q: 'A security review looks at four agent deployments. Which one is NOT exposed to data exfiltration through indirect prompt injection?',
    o: ['Reads a private repo, reads public GitHub issues, can open PRs on a public repo',
        'Reads the user\'s inbox and processes incoming mail, can fetch any URL with GET',
        'Reads private documents that may contain third-party text, renders Markdown images in the chat UI',
        'Summarises untrusted web pages and writes to a local scratch file, with no network access and no private data'], a: 'd',
    s: ['Exfiltration needs the "lethal trifecta" (Willison, 2025): access to private data, exposure to untrusted content, and a way to send data out.',
        '(a) has all three, since a public PR is an outbound channel. (b) can leak data in the query string of a GET request. (c) makes a request to an attacker\'s URL when it renders an image. (d) has no private data and no outbound channel, so it is safe.'] },
];

const secC = [
  { id: 'C1', q: 'How many trailing zeros does 100! have when written in base 12?', o: ['97', '48', '24', '33'], a: 'b',
    s: ['12 = 2² × 3. The power of 2 in 100! is 50 + 25 + 12 + 6 + 3 + 1 = 97, which gives 48 factors of 4.',
        'The power of 3 is 33 + 11 + 3 + 1 = 48. The number of trailing zeros is min(48, 48) = 48.'] },
  { id: 'C2', q: 'How many ordered pairs of positive integers (x, y) satisfy 1/x + 1/y = 1/12?', o: ['8', '9', '15', '16'], a: 'c',
    s: ['Clearing denominators gives (x − 12)(y − 12) = 144. If both factors were negative, each would be at least −11 and their product at most 121 < 144, so both factors must be positive divisors.',
        '144 = 2⁴ × 3² has 5 × 3 = 15 divisors, so there are 15 ordered pairs.'] },
  { id: 'C3', q: 'What is the expected number of rolls of a fair die until you get two consecutive 6s?', o: ['36', '12', '42', '30'], a: 'c',
    s: ['Let E₀ be the expected rolls from the start and E₁ the expected rolls just after a 6.',
        'E₁ = 1 + (5/6)E₀ and E₀ = 1 + (1/6)E₁ + (5/6)E₀, so E₀ = 6 + E₁.',
        'Substituting: E₀ = 7 + (5/6)E₀, which gives E₀ = 42.'] },
  { id: 'C4', q: 'What day of the week was 15 August 1947?', o: ['Thursday', 'Friday', 'Saturday', 'Sunday'], a: 'b',
    s: ['Count odd days. 1600 years give 0. 300 years give 3 × 5 = 15, which is 1 mod 7.',
        '1901–1946 is 46 years with 11 leap years, so 57 odd days, which is 1 mod 7.',
        '1 January to 15 August 1947 is 31 + 28 + 31 + 30 + 31 + 30 + 31 + 15 = 227 days, which is 3 mod 7.',
        'The total is 0 + 1 + 1 + 3 = 5, and with Sunday = 0 that is Friday.'] },
  { id: 'C5', q: 'What is the remainder when 2²⁰²⁶ is divided by 1001?', o: ['443', '857', '529', '933'], a: 'd',
    s: ['1001 = 7 × 11 × 13.',
        'mod 7: 2³ ≡ 1 and 2026 ≡ 1 (mod 3), so the remainder is 2. mod 11: 2¹⁰ ≡ 1 and 2026 ≡ 6 (mod 10), so 64 ≡ 9. mod 13: 2¹² ≡ 1 and 2026 ≡ 10 (mod 12), so 1024 ≡ 10.',
        'By CRT, x ≡ 2 (mod 7), 9 (mod 11) and 10 (mod 13), which gives x = 933. Check: 933 = 7·133 + 2 = 11·84 + 9 = 13·71 + 10.'] },
  { id: 'C6', q: 'One coin in a pile is counterfeit, but you don\'t know whether it is heavier or lighter. With 4 weighings on a balance and no extra genuine coin, what is the largest pile in which you can always find the fake and say whether it is heavier or lighter?',
    o: ['40', '39', '81', '27'], a: 'b',
    s: ['Four weighings have 3⁴ = 81 outcomes, and N coins create 2N cases (each coin heavy or light).',
        'Without a reference coin, the first weighing cannot use every outcome, and the known maximum (Dyson, 1946) is (3ⁿ − 3)/2 = (81 − 3)/2 = 39.'] },
  { id: 'C7', q: 'Find the next term: 2, 3, 10, 15, 26, 35, 50, ?', o: ['63', '65', '61', '67'], a: 'a',
    s: ['The terms are n² + 1 for odd n and n² − 1 for even n: 1+1, 4−1, 9+1, 16−1, 25+1, 36−1, 49+1.',
        'The next term is 64 − 1 = 63.'] },
  { id: 'C8', q: 'A and B start from the same point on a 600 m circular track. They run in opposite directions at 5 m/s and 7 m/s and never stop. At how many distinct points on the track do they meet?',
    o: ['6', '2', '12', '24'], a: 'c',
    s: ['Their relative speed is 12 m/s, so they meet every 600/12 = 50 s. A runs 250 m between meetings, so the meeting points are at 250k mod 600.',
        'gcd(250, 600) = 50, so there are 600/50 = 12 distinct points. Equivalently, (5 + 7)/gcd(5, 7) = 12.'] },
  { id: 'C9', q: 'Six letters are placed in six addressed envelopes. In how many ways do exactly two letters go into their correct envelopes?',
    o: ['135', '90', '265', '120'], a: 'a',
    s: ['Choose the 2 correctly placed letters: C(6, 2) = 15 ways. The remaining 4 must all be misplaced: D₄ = 9 ways.',
        '15 × 9 = 135.'] },
  { id: 'C10', q: 'A triangle has sides 13, 14 and 15. What is the distance between its incentre and its circumcentre?',
    o: ['1', '√65 / 8', '√65 / 4', '1/8'], a: 'b',
    s: ['s = 21 and the area is √(21 × 8 × 7 × 6) = 84. The inradius is r = 84/21 = 4 and the circumradius is R = abc/(4 × area) = 2730/336 = 65/8.',
        'Euler\'s formula gives OI² = R(R − 2r) = (65/8)(1/8) = 65/64, so OI = √65/8.'] },
];

module.exports = { secA, secML, secGA, secAG, secC };
